---
- name: Get execution node
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: awx
      set_fact:
        exec_node: "{{ awx_execution_node | default('') }}"


    - debug:
        msg: "Execution node: {{ exec_node }}"
