---
- name: Get execution node
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Get Execution Node 
      shell: hostname
      register: resultnode
      delegate_to: ansibletest01


    - debug:
        msg: "Execution node: {{ resultnode}}"
