---
- name: Install Instana Agent
  hosts: all
  become: yes
  gather_facts: no

  vars:
    source_server: instana_repo
    instana_path: /appl/instana-installers

  tasks:

  - name: Find Instana RPM on source server
    find:
      paths: "{{ instana_path }}"
      patterns: "*.rpm"
    delegate_to: "{{ source_server }}"
    register: instana_rpm

  - name: Copy Instana RPM to target server
    shell: scp {{ instana_rpm.files[0].path }} {{ inventory_hostname }}:/tmp/
    delegate_to: "{{ source_server }}"

  - name: Install Instana RPM
    yum:
      name: "/tmp/{{ instana_rpm.files[0].path | basename }}"
      state: present
   
  - name: Enable Instana service
    systemd:
      name: instana-agent
      enabled: yes

  - name: Backup configuration file
    shell: mv /opt/instana/agent/etc/instana/configuration.yaml /opt/instana/agent/etc/instana/configuration.yaml.bck
    ignore_errors: yes

  - name: Backup backend file
    shell: mv /opt/instana/agent/etc/instana/com.instana.agent.main.sender.backend.cfg /opt/instana/agent/etc/instana/com.instana.agent.main.sender.backend.cfg.bck
    ignore_errors: yes

  - name: Copy configuration.yaml
    shell: scp {{ instana_path }}/configuration.yaml {{ inventory_hostname }}:/opt/instana/agent/etc/instana/
    delegate_to: "{{ source_server }}"

  - name: Copy backend config
    shell: scp {{ instana_path }}/com.instana.agent.main.sender.backend.cfg {{ inventory_hostname }}:/opt/instana/agent/etc/instana/
    delegate_to: "{{ source_server }}"

#  - name: Enable Instana service
   # systemd:
   #   name: instana-agent
    #  enabled: yes

  - name: Restart Instana Agent
    systemd:
      name: instana-agent
      state: restarted
