---
- name: Install and Configure Instana
  hosts: all
  become: yes

  vars:
    source_host: 156.150.36.184
    rpm_file: /appl/instana-installers/linux/instana-agent-static-j9-20260311-1055.x86_64.rpm
    config_files:
      - /appl/instana-installers/linux/configuration.yaml
      - /appl/instana-installers/linux/com.insta.agent.main.sender.backend.cfg
    local_temp_dir: /tmp
    remote_temp_dir: /tmp/deployment
    dest_config_dir: /tmp/deployment/install
    service_name: myapp
    backup_suffix: ".bak"

  tasks:


    - name: Create temp dir on control node
      file:
        path: "{{ local_temp_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true


    - name: Fetch RPM from source server
      become: true
      fetch:
        src: "{{ rpm_file }}"
        dest: "{{ local_temp_dir }}/"
        flat: yes
      delegate_to: "{{ source_host }}"
      run_once: true

    - name: Fetch config files from source server
      fetch:
        src: "{{ item }}"
        dest: "{{ local_temp_dir }}/"
        flat: yes
      loop: "{{ config_files }}"
      delegate_to: "{{ source_host }}"
      run_once: true


    - name: Ensure temp directory exists on target
      file:
        path: "{{ remote_temp_dir }}"
        state: directory
        mode: '0755'


    - name: Copy RPM to target
      copy:
        src: "{{ local_temp_dir }}/{{ rpm_file | basename }}"
        dest: "{{ remote_temp_dir }}/"
        mode: '0644'

    - name: Copy config files to target
      copy:
        src: "{{ local_temp_dir }}/{{ item | basename }}"
        dest: "{{ remote_temp_dir }}/"
        mode: '0644'
      loop: "{{ config_files }}"


    - name: Install RPM package
      dnf:
        name: "{{ remote_temp_dir }}/{{ rpm_file | basename }}"
        state: present
        disable_gpg_check: yes

    - name: Backup existing config files
      copy:
        src: "{{ dest_config_dir }}/{{ item | basename }}"
        dest: "{{ dest_config_dir }}/{{ item | basename }}{{ backup_suffix }}"
        remote_src: yes
      ignore_errors: yes
      loop: "{{ config_files }}"

    - name: Deploy new config files
      copy:
        src: "{{ remote_temp_dir }}/{{ item | basename }}"
        dest: "{{ dest_config_dir }}/{{ item | basename }}"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes

      loop: "{{ config_files }}"


    - name: Restart service
      service:
        name: "{{ service_name }}"
        state: restarted
