---
- name: Install Instana Agent
  hosts: all
  become: yes
  gather_facts: no

  vars:
    config_dir: /opt/instana/agent/etc/instana

  tasks:

  - name: Copy Instana RPM to server
    copy:
      src: instana-agent-static.rpm   # instana agent rpm file 
      dest: /tmp/instana-agent.rpm

  - name: To install Instana RPM
    yum:
      name: /tmp/instana-agent.rpm
      state: present

  - name: To enable Instana service
    service:
      name: instana-agent
      enabled: yes

  - name: Backup configuration.yaml
    command: mv {{ instana_config_dir }}/configuration.yaml {{ instana_config_dir }}/configuration.yaml.bck
    ignore_errors: yes

  - name: Backup backend config
    command: mv {{ instana_config_dir }}/com.instana.agent.main.sender.backend.cfg {{ instana_config_dir }}/com.instana.agent.main.sender.backend.cfg.bck
    ignore_errors: yes

  - name: Copy new configuration.yaml
    copy:
      src: configuration.yaml    # need to provide file path 
      dest: "{{ instana_config_dir }}/configuration.yaml"
      
  - name: Copy backend config file
    copy:
      src: com.instana.agent.main.sender.backend.cfg     # need to provide file path 
      dest: "{{ instana_config_dir }}/com.instana.agent.main.sender.backend.cfg"
      
  - name: Restart Instana agent
    service:
      name: instana-agent
      state: restarted
