# patil_rajnandini_ansible
---
- name: playook to check connectivity and print the msg
  hosts: all
  tasks:
  - name: to check the connectivity
    ping:
  - name: to print the msg
    debug:
      msg: "Hello World"
